#------------------------------------------------------------------------
#                       LoneWolves-PunishGUI
#                          lonewolves.net
#                      lonewolves.net/discord
#                   Coded by DeathRealms and EzJamo
#------------------------------------------------------------------------

Punish Times:
  - '&c&lPunish Times'
  - '&7&m----------------------------------------------------'
  - '&cSpam &8- &730m Mute'
  - '&cStaff/Player Disrespect &8- &73h Mute'
  - '&cFailure to use common sense &8- &73h Mute'
  - '&cDeath Remarks/Threats &8- &73d Mute'
  - '&cRacism &8- &71d Mute'
  - '&cRacism (Hard R) &8- &73d Mute'
  - '&cHacked Clients &8- &714d Ban (First), 21d (Second), 30d (Third)'
  - '&cAbusing Helpop &8- &73h Ban'
  - '&cGeneral Toxicity &8- &71d Ban'
  - '&cAlts over limit of 10 &8- &7Perm Ban'
  - '&cDDoS Threats &8- &7Perm Ban'
  - '&cAdvertising &8- &7Perm Ban'