name: LW-PunishGUI
main: me.deathrealms.PunishGUI
version: 2.3
description: PunishGUI plugin coded by the LoneWolves Development Team. 
author: DeathRealms

commands:
  punish:
   aliases: [p]
