name: LW-PunishGUI
main: me.deathrealms.punishgui.PunishGUI
version: 2.0
description: PunishGUI plugin coded by the LoneWolves Development Team. 
author: DeathRealms & EzJamo

commands:
  punish:
   aliases: [p]